#config_version=5

#coil numbers are labelled in silkscreen on the board

  #There are multiple ways to configure flippers, use the one that
  #  matches your hardware
  
coils:
    c_pop_bmp_left:
        number: 0-0-0
        tags: pop1
        default_pulse_ms: 15
    c_shooter_launch:
        number: 0-0-1
        tags: launch_kicker
        default_pulse_ms: 25
    c_trough_eject:
        number: 0-0-2
        tags: trough
        default_pulse_ms: 25        
    c_slingshot_right:
        number: 0-0-3
        tags: slingshot
        default_pulse_ms: 8
        default_recycle: true
        platform_settings:
            recycle_factor: 3
    c_slingshot_left:
        number: 0-0-4
        tags: slingshot
        default_pulse_ms: 8
        default_recycle: true
        platform_settings:
            recycle_factor: 3
    c_saucer_left:
        number: 0-0-5
        tags: escape_room
        default_pulse_ms: 10
    c_drop_target_left:
        number: 0-0-6
        tags: left_drop_target
        default_pulse_ms: 25
    c_drop_target_top:
        number: 0-0-7
        tags: top_drop_target
        default_pulse_ms: 30
    c_pop_bmp_right:
        number: 0-0-12
        tags: pop2
        default_pulse_ms: 15
    c_pop_bmp_bottom:
        number: 0-0-13
        tags: pop3
        default_pulse_ms: 15
    c_saucer_right:
        number: 0-0-14
        tags: extra_ball
        default_pulse_ms: 15
    c_bell:
        number: 0-0-15
        tags: bell
        default_pulse_ms: 10

    c_flipper_left_main:
        number: 1-0-1
        default_pulse_ms: 18
    c_flipper_left_hold:
        number: 1-0-2
        allow_enable: true
        default_hold_power: 1.0
        default_pulse_ms: 13
    c_flipper_right_main:
        number: 1-0-6
        default_pulse_ms: 18
    c_flipper_right_hold:
        number: 1-0-7
        allow_enable: true
        default_hold_power: 1.0
        default_pulse_ms: 13
    c_flipper_upper_right_main:
        number: 1-0-4
        default_pulse_ms: 18
    c_flipper_upper_right_hold:
        number: 1-0-5
        allow_enable: true
        default_hold_power: 1.0
        default_pulse_ms: 13
        
# Satellite Board
    led_flasher_1:
        number: 3-0-0
        allow_enable: true
        default_hold_power: 0.2
        default_pulse_ms: 5
    led_flasher_2:
        number: 3-0-1
        allow_enable: true
        default_hold_power: 0.2
        default_pulse_ms: 5
        